-- Drop tables in correct order
DROP TABLE IF EXISTS public.cart;
DROP TABLE IF EXISTS public.vehicle_upgrades;
DROP TABLE IF EXISTS public.upgrades;
DROP TABLE IF EXISTS public.inventory;
DROP TABLE IF EXISTS public.account;
DROP TABLE IF EXISTS public.classification;

-- Create ENUM type
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- Create classification table
CREATE TABLE public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classification_name VARCHAR NOT NULL
);

-- Create account table
CREATE TABLE public.account (
  account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_firstname VARCHAR NOT NULL,
  account_lastname VARCHAR NOT NULL,
  account_email VARCHAR UNIQUE NOT NULL,
  account_password VARCHAR NOT NULL,
  account_type account_type DEFAULT 'Client'
);

-- Create inventory table
CREATE TABLE public.inventory (
  inv_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inv_make VARCHAR NOT NULL,
  inv_model VARCHAR NOT NULL,
  inv_year CHAR(4) NOT NULL,
  inv_description TEXT NOT NULL,
  inv_image VARCHAR NOT NULL,
  inv_thumbnail VARCHAR NOT NULL,
  inv_price NUMERIC(9,0) NOT NULL,
  inv_miles INT NOT NULL,
  inv_color VARCHAR NOT NULL,
  classification_id INT NOT NULL,
  CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);

-- Create upgrades table
CREATE TABLE public.upgrades (
  upgrade_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upgrade_name VARCHAR NOT NULL,
  upgrade_description TEXT NOT NULL,
  upgrade_price NUMERIC(9,2) NOT NULL,
  upgrade_image VARCHAR,
  upgrade_available BOOLEAN DEFAULT TRUE,
  created_date TIMESTAMP DEFAULT NOW()
);

-- Create vehicle_upgrades junction table
CREATE TABLE public.vehicle_upgrades (
  vehicle_upgrade_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inv_id INT NOT NULL,
  upgrade_id INT NOT NULL,
  compatibility_notes TEXT,
  added_date TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_upgrade FOREIGN KEY (upgrade_id)
    REFERENCES public.upgrades (upgrade_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  UNIQUE(inv_id, upgrade_id)
);

-- Create cart table
CREATE TABLE public.cart (
  cart_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INT NOT NULL,
  inv_id INT NOT NULL,
  upgrade_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  added_date TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_account FOREIGN KEY (account_id)
    REFERENCES public.account (account_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_inventory_cart FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_upgrade_cart FOREIGN KEY (upgrade_id)
    REFERENCES public.upgrades (upgrade_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  UNIQUE(account_id, inv_id, upgrade_id)
);

-- Insert classification data
INSERT INTO public.classification (classification_name) VALUES
  ('Custom'),
  ('Sport'),
  ('SUV'),
  ('Truck'),
  ('Sedan');

-- Insert inventory data (complete dataset)
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description,
    inv_image, inv_thumbnail, inv_price, inv_miles,
    inv_color, classification_id
) VALUES
  ('Chevy', 'Camaro', '2018', 'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!', '/images/vehicles/camaro.jpg', '/images/vehicles/camaro-tn.jpg', 25000, 101222, 'Silver', 2),
  ('Batmobile', 'Custom', '2007', 'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during rush hour.', '/images/vehicles/batmobile.jpg', '/images/vehicles/batmobile-tn.jpg', 65000, 29887, 'Black', 1),
  ('FBI', 'Surveillance Van', '2016', 'Do you like police shows? You will feel right at home driving this van, comes complete with survalence equipments for and extra fee of $2,000 a month.', '/images/vehicles/survan.jpg', '/images/vehicles/survan-tn.jpg', 20000, 19851, 'Brown', 1),
  ('Dog ', 'Car', '1997', 'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.', '/images/vehicles/dog-car.jpg', '/images/vehicles/dog-car-tn.jpg', 35000, 71632, 'White', 1),
  ('Jeep', 'Wrangler', '2019', 'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the the rocks or in the mud!', '/images/vehicles/wrangler.jpg', '/images/vehicles/wrangler-tn.jpg', 28045, 41205, 'Yellow', 3),
  ('Lamborghini', 'Adventador', '2016', 'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ', '/images/vehicles/adventador.jpg', '/images/vehicles/adventador-tn.jpg', 417650, 71003, 'Blue', 2),
  ('Aerocar International', 'Aerocar', '1963', 'Are you sick of rushhour trafic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!', '/images/vehicles/aerocar.jpg', '/images/vehicles/aerocar-tn.jpg', 700000, 18956, 'Red', 1),
  ('Monster', 'Truck', '1995', 'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you traction needed to jump and roll in the mud.', '/images/vehicles/monster-truck.jpg', '/images/vehicles/monster-truck-tn.jpg', 150000, 3998, 'purple', 1),
  ('Cadillac', 'Escalade', '2019', 'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.', '/images/vehicles/escalade.jpg', '/images/vehicles/escalade-tn.jpg', 75195, 41958, 'Black', 4),
  ('GM', 'Hummer', '2016', 'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.', '/images/vehicles/hummer.jpg', '/images/vehicles/hummer-tn.jpg', 58800, 56564, 'Yellow', 4),
  ('Mechanic', 'Special', '1964', 'Not sure where this car came from. however with a little tlc it will run as good a new.', '/images/vehicles/mechanic.jpg', '/images/vehicles/mechanic-tn.jpg', 100, 200125, 'Rust', 5),
  ('Ford', 'Model T', '1921', 'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.', '/images/vehicles/model-t.jpg', '/images/vehicles/model-t-tn.jpg', 30000, 26357, 'Black', 5),
  ('Mystery', 'Machine', '1999', 'Scooby and the gang always found luck in solving their mysteries because of there 4 wheel drive Mystery Machine. This Van will help you do whatever job you are required to with a success rate of 100%.', '/images/vehicles/mystery-van.jpg', '/images/vehicles/mystery-van-tn.jpg', 10000, 128564, 'Green', 1),
  ('Spartan', 'Fire Truck', '2012', 'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and a 1000 gallon tank.', '/images/vehicles/fire-truck.jpg', '/images/vehicles/fire-truck-tn.jpg', 50000, 38522, 'Red', 4),
  ('Ford', 'Crown Victoria', '2013', 'After the police force updated their fleet these cars are now available to the public! These cars come equiped with the siren which is convenient for college students running late to class.', '/images/vehicles/crwn-vic.jpg', '/images/vehicles/crwn-vic-tn.jpg', 10000, 108247, 'White', 5);

-- Insert upgrades data
INSERT INTO public.upgrades (upgrade_name, upgrade_description, upgrade_price, upgrade_image) VALUES
  ('Flux Capacitor', 'Travel through time with our premium flux capacitor installation. Requires 1.21 gigawatts of power (not included).', 12100.00, '/images/upgrades/flux-cap.webp'),
  ('Flame Decals', 'Add racing flame decals for that classic time-traveling look. High-quality vinyl that lasts for years.', 400.00, '/images/upgrades/flame.webp'),
  ('Stainless Steel Hub Caps', 'Premium stainless steel hub caps specially designed to match the iconic look of classic vehicles.', 850.00, '/images/upgrades/hub-cap.webp'),
  ('Time Traveler Package', 'Express your time traveling adventures with our special edition bumper stickers and decals.', 120.00, '/images/upgrades/bumper_sticker.webp'),
  ('Premium Sound System', 'Upgrade to our premium 10-speaker sound system with subwoofer and noise cancellation technology.', 1200.00, '/images/upgrades/sound-system.jpg'),
  ('Leather Interior', 'Luxury leather seats with heating and cooling functions for maximum comfort.', 2500.00, '/images/upgrades/leather-interior.jpg'),
  ('Performance Exhaust', 'High-performance exhaust system for improved sound and better engine efficiency.', 800.00, '/images/upgrades/exhaust.jpg'),
  ('LED Headlight Upgrade', 'Crystal-clear LED headlights for improved visibility and modern styling.', 450.00, '/images/upgrades/led-lights.jpg'),
  ('Sunroof Package', 'Power sunroof with tinted glass and rain-sensing automatic closure.', 1500.00, '/images/upgrades/sunroof.jpg'),
  ('Navigation System', 'Advanced GPS navigation with real-time traffic updates and voice control.', 900.00, '/images/upgrades/navigation.jpg');

-- Associate upgrades with vehicles (vehicle_upgrades junction table)
INSERT INTO public.vehicle_upgrades (inv_id, upgrade_id, compatibility_notes) VALUES
  -- Delorean (Batmobile) upgrades
  (2, 1, 'Perfect for time travel applications'),
  (2, 2, 'Classic look for time-traveling vehicles'),
  (2, 3, 'Matches stainless steel body'),
  (2, 4, 'Themed for temporal displacement'),
  -- Sports car upgrades
  (1, 5, 'Enhanced audio for sports car experience'),
  (1, 6, 'Premium interior for luxury sports car'),
  (1, 7, 'Performance exhaust for better sound'),
  (6, 5, 'High-end audio for luxury sports car'),
  (6, 6, 'Luxury interior package'),
  (6, 7, 'Sport exhaust system'),
  -- SUV upgrades
  (5, 5, 'Family entertainment system'),
  (5, 8, 'Improved off-road visibility'),
  (5, 9, 'Great for outdoor adventures'),
  (9, 5, 'Luxury audio for premium SUV'),
  (9, 6, 'Premium leather package'),
  (9, 10, 'Advanced navigation for large vehicle'),
  -- Truck upgrades
  (8, 7, 'Heavy-duty exhaust for truck'),
  (8, 8, 'Enhanced lighting for off-road'),
  (14, 7, 'Commercial grade exhaust'),
  (14, 8, 'Emergency vehicle lighting'),
  -- Sedan upgrades
  (12, 5, 'Classic car audio upgrade'),
  (12, 10, 'Modern navigation for classic car'),
  (15, 5, 'Police package audio'),
  (15, 10, 'Professional grade navigation');

-- Query 4: Replace 'small interiors' with 'a huge interior'
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Create indexes for better performance
CREATE INDEX idx_cart_account_id ON public.cart(account_id);
CREATE INDEX idx_cart_inv_id ON public.cart(inv_id);
CREATE INDEX idx_cart_upgrade_id ON public.cart(upgrade_id);
CREATE INDEX idx_vehicle_upgrades_inv_id ON public.vehicle_upgrades(inv_id);
CREATE INDEX idx_vehicle_upgrades_upgrade_id ON public.vehicle_upgrades(upgrade_id);
CREATE INDEX idx_upgrades_available ON public.upgrades(upgrade_available);

-- Display success message
DO $$ 
BEGIN
    RAISE NOTICE 'Database rebuilt successfully with cart and upgrade system!';
    RAISE NOTICE 'Created tables: upgrades, vehicle_upgrades, cart';
    RAISE NOTICE 'Inserted % upgrades and % vehicle-upgrade relationships', 
        (SELECT COUNT(*) FROM public.upgrades),
        (SELECT COUNT(*) FROM public.vehicle_upgrades);
END $$;